replicaCount: 1

image:
  repository: de.icr.io/photos-test/ibm-photos-front
  tag: v0.4
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: "photos-test-de-icr-io"
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

back:
  url: "http://photos-ibm-photos-back.photos-test:8000"

dataVolume:
  name: "media"
  existingClaimName: "photos-media"
