# Generated by Django 2.2.2 on 2019-06-12 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190612_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='processing',
        ),
    ]
