# Generated by Django 2.2.2 on 2019-06-13 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_photo_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='store.Photo'),
        ),
    ]
