replicaCount: 1

image:
  repository: de.icr.io/photos-test/ibm-photos-back
  tag: v0.9
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: "photos-test-de-icr-io"
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

database:
  user: "photos"
  password: "photos"
  host: "photos-ibm-postgres-dev.photos-test"
  port: "5432"

django:
  allowed_hosts: "*"
  csrf_trusted_origins: "photos.lazowik.pl"
  redis_url: "redis://photos-redis-master.photos-test:6379/0"

dataVolume:
  name: "media"
  existingClaimName: "photos-media"
