apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "photos-media"
  namespace: "photos-test"
  annotations:
    ibm.io/auto-create-bucket: "true"
    ibm.io/auto-delete-bucket: "false"
    ibm.io/bucket: "ibm-photos-media"
    ibm.io/secret-name: "cos-write-access"
    ibm.io/endpoint: "https://s3.private.fra.eu.cloud-object-storage.appdomain.cloud"
spec:
  storageClassName: ibmc-s3fs-icp
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
