dependencies:
  - name: ibm-postgres-dev
    repository: https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
    version: 1.1.3
  - name: redis
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 8.1.1
  - name: ibm-object-storage-plugin
    repository: https://icr.io/helm/iks-charts
    version: 1.0.7
#  - name: ibmcloud-block-storage-plugin
#    repository: https://icr.io/helm/iks-charts
#    version: 1.5.0
