dependencies:
  - name: ibm-postgres-dev
    repository: https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
    version: 1.1.3
#  - name: ibmcloud-block-storage-plugin
#    repository: https://icr.io/helm/iks-charts
#    version: 1.5.0
