ibm-postgres-dev:
  persistence:
    enabled: false
    useDynamicProvisioning: false
  dataVolume:
    storageClass: "ibmc-block-bronze"
    size: 1Gi
  resources:
    requests:
      memory: 128Mi
      cpu: 10m
  database:
    user: "photos"
    password: "photos"
    name: "postgres"
  service:
    type: "ClusterIP"

redis:
  cluster:
    enabled: false
  usePassword: false
  resources:
    memory: 128Mi
    cpu: 10m
  master:
    persistence:
      enabled: false
