replicaCount: 1

image:
  repository: de.icr.io/photos-test/ibm-photos-back
  tag: v0.10
  command:
    - "celery"
    - "-A"
    - "photos"
    - "beat"
    - "-l"
    - "info"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: "photos-test-de-icr-io"
nameOverride: ""
fullnameOverride: ""

database:
  user: "photos"
  password: "photos"
  host: "photos-ibm-postgres-dev.photos-test"
  port: "5432"

django:
  allowed_hosts: "*"
  redis_url: "redis://photos-redis-master.photos-test:6379/0"